### ISSUE TITLE
Add `jitpack.yml`

### ISSUE THREAD

**Issue by jo-elimu** [elimu-ai/analytics#141]
See example at https://github.com/elimu-ai/content-provider/blob/main/jitpack.yml

**Comment by jpascoe32fb** [comment]
Can I be assigned to this? I've attempted a PR request for this issue.

**Comment by nya-elimu** [comment]
> Can I be assigned to this?

@jpascoe32fb Sent you an invite to join our GitHub organization (so that you can self-assign yourself to issues).
